export interface ProjectProps {
  title: string;
  description: string;
  icon: string;
  preview?: string;
  link: string;
  color?: string;
  darkColor?: string;
  gradient?: string[];
  darkGradient?: string[];
  tag?: string;
  stack?: string[];
}

export const projects: ProjectProps[] = [
  {
    title: 'Blueprint',
    description: 'Dashboard for creating Android icon packs.',
    icon: '/assets/images/projects/android/blueprint.png',
    preview: '/assets/images/projects/android/blueprint-preview.png',
    link: 'https://github.com/jahirfiquitiva/Blueprint/',
    color: '#4d8af0',
    tag: 'android',
    stack: ['android', 'kotlin', 'material design'],
  },
  {
    title: 'Frames',
    description: 'frames',
    icon: '/assets/images/projects/android/frames.png',
    preview: '/assets/images/projects/android/frames-preview.png',
    link: 'https://github.com/jahirfiquitiva/Frames/',
    color: '#35b4ef',
    tag: 'android',
    stack: ['android', 'kotlin', 'material design'],
  },
  {
    title: 'Kuper',
    description: 'kuper',
    icon: '/assets/images/projects/android/kuper.png',
    preview: '/assets/images/projects/android/kuper-preview.png',
    link: 'https://github.com/jahirfiquitiva/Kuper/',
    color: '#6673C0',
    tag: 'android',
    stack: ['android', 'kotlin', 'material design'],
  },
  {
    title: 'Pals',
    description: 'pals',
    icon: '/assets/images/projects/android/pals.png',
    preview: '/assets/images/projects/android/pals-preview.png',
    link: 'https://jahir.xyz/PalsApp',
    color: '#4285F4',
    tag: 'android',
    stack: ['android', 'kotlin', 'material design'],
  },
  {
    title: 'Tap',
    description: 'tap',
    icon: '/assets/images/projects/android/tap.png',
    preview: '/assets/images/projects/android/tap-preview.png',
    link: 'https://jahir.xyz/TapApp',
    color: '#E69494',
    tag: 'android',
    stack: ['android', 'kotlin', 'material design'],
  },
  {
    title: 'ChipView',
    description: 'chipview',
    icon: '/assets/images/projects/android/chipview.png',
    preview: '/assets/images/projects/android/chipview-preview.png',
    link: 'https://github.com/jahirfiquitiva/ChipView/',
    color: '#3E95FB',
    tag: 'android',
    stack: ['android', 'kotlin', 'material design'],
  },
  {
    title: 'FABsMenu',
    description: 'fabsmenu',
    icon: '/assets/images/projects/android/fabsmenu.png',
    preview: '/assets/images/projects/android/fabsmenu-preview.png',
    link: 'https://github.com/jahirfiquitiva/FABsMenu/',
    color: '#eb3b75',
    tag: 'android',
    stack: ['android', 'java', 'material design'],
  },
  {
    title: 'Dashbud',
    description: 'dashbud',
    icon: '/assets/images/projects/web/setup.png',
    link: '/dashsetup/',
    preview: '/assets/images/projects/web/dashbud-preview.png',
    color: '#9853fd',
    tag: 'web',
    stack: ['HTLM5', 'css3', 'javascript', 'react'],
  },
  {
    title: 'Changes',
    description: 'changes',
    icon: '/assets/images/projects/web/changes.png',
    preview: '/assets/images/projects/web/changes-preview.png',
    link: '/changes/',
    color: '#27b6c0',
    tag: 'web',
    stack: ['HTLM5', 'css3', 'typescript', 'react', 'nextjs'],
  },
  {
    title: 'Prev Websites',
    description: 'prevweb',
    icon: '/assets/images/projects/web/prev-websites.png',
    link: 'https://github.com/jahirfiquitiva/prev-websites/',
    preview: '/assets/images/projects/web/websites-preview.png',
    color: '#88a4e6',
    tag: 'web',
    stack: ['HTLM5', 'css3', 'javascript'],
  },
  {
    title: 'BoyaConf',
    description: 'boyaconf',
    icon: '/assets/images/projects/other/boyaconf.png',
    link: 'https://boyaconf.com',
    preview: '/assets/images/projects/other/boyaconf-preview.png',
    color: '#4dcc89',
    darkColor: '#00202b',
    tag: 'conference',
    stack: ['community', 'HTLM5', 'css3', 'javascript'],
  },
  {
    title: 'Sliding Puzzle',
    description: 'sliding',
    icon: '/assets/images/projects/other/puzzle.png',
    link: 'https://jahir.xyz/SlidingPuzzle',
    preview: '/assets/images/projects/other/sliding-puzzle-preview.png',
    color: '#929292',
    tag: 'python',
    stack: ['python'],
  },
  {
    title: 'Stan',
    description: 'stan',
    icon: '/assets/images/projects/other/stan.png',
    link: 'https://github.com/jahirfiquitiva/stanbot/',
    color: '#FC8303',
    tag: 'python',
    stack: ['python'],
  },
  {
    title: 'More',
    description: 'other',
    icon: '/assets/images/projects/other/more.png',
    link: 'https://jahir.xyz/github',
    color: '#92a3b5',
    tag: 'other',
    stack: ['git'],
  },
];
